<?php
/** @var boolean $error */
/** @var string $login */
?>

<?php $this->layout('layout::default', ['title' => 'Home']) ?>

<div class="form-auth">
    <div class="row">
        <div class="panel panel-primary">
            <div class="panel-heading"></div>
            <div class="panel-body">
                <form action="/" method="post">
                    <div class="form-group">
                        <input type="text" name="login" class="form-control" placeholder="Login" value="<?= $login ?>">
                    </div>
                    <div class="form-group">
                        <input type="password" name="password" class="form-control" placeholder="Password">
                    </div>
                    <?php if ($error): ?>
                        <div class="alert alert-danger">Credential is invalid</div>
                    <?php endif; ?>
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a href="/register" class="float-right">Registration</a>
                </form>
            </div>
        </div>
    </div>
</div>
