<?php
/** @var boolean $success */
/** @var string $login */
?>

<?php $this->layout('layout::default', ['title' => 'Home']) ?>

<div class="form-auth">
    <div class="row">
        <?php if ($success): ?>
        <div class="panel panel-success">
            <div class="panel-heading">User "<?= $login ?>" registered</div>
            <div class="panel-body">
                <span class="float-right">Go to <a href="/">Login form</a></span>
            </div>
        </div>
        <?php else: ?>
        <div class="panel panel-default">
            <div class="panel-body">
                <form action="/register" method="post">
                    <div class="form-group">
                        <input type="text" name="login" class="form-control" placeholder="Login">
                    </div>
                    <div class="form-group">
                        <input type="password" name="password" class="form-control" placeholder="Password">
                    </div>
                    <button type="submit" class="btn btn-primary">Register</button>
                </form>
            </div>
        </div>
        <?php endif; ?>
    </div>
</div>
