<?php
/** @var string $nick */
/** @var string $open_key */
?>

<?php $this->layout('layout::profile', ['title' => 'Profile - Edit']) ?>

<div id="profile-edit-form"></div>

<?php $this->start('javascript') ?>
<script language="JavaScript">
    ReactDOM.render(
        React.createElement(
            ProfileEditForm,
            {
                nick: '<?= $nick ?>',
                open_key: <?= json_encode($open_key) ?>
            },
            null
        ),
        document.getElementById('profile-edit-form')
    );
</script>
<?php $this->stop() ?>