<?php
/** @var string $nick */
/** @var array $errors */
?>

<?php $this->layout('layout::profile', ['title' => 'Profile - Edit']) ?>

<div class="row">
    <div class="col-sm-4">
        <div class="panel panel-primary">
            <div class="panel-heading">Profile</div>
            <div class="panel-body">
                <form action="/profile/edit" method="post">
                    <div class="form-group">
                        <input type="text" name="nick" class="form-control" placeholder="Nick" value="<?= $nick ?>">
                    </div>
                    <?php if (count($errors) > 0): ?>
                        <div class="alert alert-danger"><?= implode('<br />', $errors) ?></div>
                    <?php endif; ?>
                    <button type="submit" class="btn btn-primary">Save</button>
                </form>
            </div>
        </div>
    </div>
</div>
