<?php
/** @var array $profile */
/** @var array $conversations */
?>

<?php $this->layout('layout::profile', ['title' => 'Profile']) ?>

<div class="row">
    <div class="col-sm-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <a href="/profile/edit" class="float-right">Edit</a>
                Profile
            </div>
            <div class="panel-body">
                Nick: <?= $profile['nick'] ?><br>
                Open key: <?php if ($profile['has_open_key']): ?><span class="zf-green">Ok</span><?php else: ?><span class="red">empty</span><?php endif ?><br>
                Private key: <span id="private_key_ok" class="zf-green" style="display:none;">Ok</span><span id="private_key_empty" style="display:none;"><a class="red" href="/profile">Not selected</a></span>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <a href="/conversation/create" class="float-right">Create</a>
                Conversations
            </div>
            <div class="panel-body">
                <div class="hidden" id="conversations">
                    <?= json_encode($conversations) ?>
                </div>
                <div id="conversations_list"></div>
            </div>
        </div>
    </div>
</div>

<?php $this->start('javascript') ?>
<script src="/js/lib/sha256.js"></script>
<script src="/js/lib/tripledes.js"></script>
<script src="/js/lib/jsencrypt.min.js"></script>
<script src="/js/crypto.js"></script>
<script src="/js/profile/index.js"></script>
<?php $this->stop() ?>