<?php $this->layout('layout::default', ['title' => 'Login']) ?>

<form action="/login" method="post">
  <div class="form-group">
    <label for="login">Login</label>
    <input type="text" name="login" class="form-control" id="login" placeholder="Enter login">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
