<?php
/** @var string $login */
/** @var boolean $error */
?>

<?php $this->layout('layout::default', ['title' => 'Login']) ?>

<div class="row">
    <div class="col-sm-4">
        <div class="panel panel-default">
            <div class="panel-heading">Authentication</div>
            <div class="panel-body">
                <form action="/login" method="post">
                    <div class="form-group">
                        <input type="text" name="login" class="form-control" placeholder="Login" value="<?= $login ?>">
                    </div>
                    <div class="form-group">
                        <input type="password" name="password" class="form-control" placeholder="Password">
                    </div>
                    <?php if ($error): ?>
                        <div class="alert alert-danger">Credential is invalid</div>
                    <?php endif; ?>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
