<?php
?>

<?php $this->layout('layout::profile', ['title' => 'Chat - Create']) ?>

<div class="row">
    <div class="col-sm-6">
        <div class="panel panel-primary">
            <div class="panel-heading">New Chat</div>
            <div class="panel-body">
                <form action="/chat/create" method="post" id="chat_create_form">
                    <div class="form-group">
                        <label for="theme">Theme</label>
                        <input type="text" name="theme" id="theme" class="form-control" />
                    </div>
                    <div class="form-group float-right">
                        <button type="button" class="btn btn-primary" id="button_cancel">Cancel</button>
                        <button type="submit" class="btn btn-primary">Create</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<?php $this->start('javascript') ?>
<script src="/js/chat.js"></script>
<?php $this->stop() ?>